apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-example
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  #  - ReadWriteMany
  #  - ReadOnlyMany
  #  - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  #mountOptions:
  #  - hard
  #  - nfsvers=4.1
  hostPath:
    path: /mnt/data
  #nfs:
  #  path: /tmp
  #  server: 172.17.0.2