apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-example
  namespace: namespace
  labels:
    app: namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi